### ISSUE TITLE
initialize $rootScope.i18n exactly once

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar-angular-adapter#27]
The $rootScope.i18n is currently re-initialized for each widget instance.

**Comment by jpommerening** [comment]
In a similar fashion, `$rootScope` is not initialized at all if (during tests) a new adapter is created. This results in an exception when `$rootScope.i18n` is to be re-initialized while `$rootScope` is still undefined.

I moved some code around so that now the internal `$rootScope` variable is set even if another adapter is created and `injectorCreated` is `true`. This turns out to be the ideal point to set the `i18n` property.

@alex3683, @x1B: pls make sure I did not commit some unspeakable horrors.

**Comment by jpommerening** [comment]
Implemented on `master` (`0.4.0`?)

**Comment by x1B** [comment]
@jpommerening it definitely makes sense to move the rootScope initialization out of the axContext initializer. 

Regarding the version: when in doubt, version is 2.0.0 for all laxar2 related changes.

**Comment by x1B** [comment]
_Closing:_ The fix for the `$rootScope.i18n` works. However, it also introduces testability problems by creating the injector much sooner than before. This will be dealt with in #25
